; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2025-10-23 at 10:09:28
; total layer number: 1
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.25
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 4260
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAMQUlEQVR4Ae3dz4tdZxkH8HdTxII0xZ
; JC25Sg1l8kNWDs0ETsYEDaILaF0gSqZMBoQqBJxFgFKXFhVi4G7MZVAy5cFeJKXCXdmIWUBuJKMAQE
; 3bjonzDO07m3c3I7c+e9954f77nn84HvsnDpTA7vee77fSYlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAac2h/OnLuaLqcAEr2i+Pp6v/eShuRP59O
; tw48kg4mgJLEqerWWrozfliN869L6aOXnkmvJIASxOvf5INqMr/9blp/5DNpXwLoQjyA3jmZru/1sB
; onTmBxEksAbYoHz4fn0v3ch1X1FTFOZE5bQCvi9W7WB9VkDOSBRu02WJ83cdo6fSitJYA65QzW503M
; wbwiAguLB8kfX003mnpYVQfyrj8Ac4sHSLy2Nf2wMpAHFlLHYH2RgbzrD8Ce5r2u0MRp69nH02oC2E
; m1B9hl/vlm2jh1KF0dfy7XH4BPxAOhzusKi+SvP0wffeHRrZNVzLLi9VAfEfhY3IMq4UH1n5+njSvH
; 0vVpn0sfEQZslh5gk7l7IW189bHtedW0z6WPCANTymA98vuX0q1HP7s1o8r9XK4/wEB0eV2hmhisv/
; il7a2k8wz89RFhSdXdA1wk776cbj3xua3XukU/lz4iLJkme4CzJAbrZ46k9SY+lz4i9FxbPcCc3Dzz
; 4HWFJj6XPiL01PEDabXNHuC0/O576VZbn8tAHnqmpMH66sHt+VKbn8tAHgpX0nWFP3y/vsH6oqetBJ
; SllMF6nKqaGqwvctryiggFGPftun4ojPODr2ydaEr6XNV+ItCRUnqA1cRrWCkztLhGMTnwjwuqTlvQ
; slJ6gKUmXk2fP7DzwF8fEVpS0mC91OT0Ew3koWGlLNgrNZOL/3L+f7n+ADUrqQdYaqqD9VkXEuojQk
; 1Kua5QanIW/+VGHxHmVFIPsNR8cC5/8V9u4mQW3yYmIE9JPcBSE9cVZl38lxt9RMhUyh2mUjO5+K/J
; /18G8rALg/W900U/0fUHmGCwPj0l9BNjnugVkUErrQdYYib/TmGXX0TEnMyCQAapxB5gSdmpB1jCFx
; HxGVae8tBiQPQA8zJeC1PqQkJ9RJaaHmB/s9PA30CepaUH2M/kDPxdf2BpuK7Q30wO/Kd9QRKnLQN5
; es11hX4mBv7XTmwP/Gf5giTmba4/0CvxC2uw3s/cvbB4P9GCQHrDYL2/yVn8lxt9RIqnB9jPxGD91a
; /NtvgvNwbyFMdgvb+pDtab+jlaEEgxDNb7mRisX1zZXvzXxs/RgkA6Y8Fef3P7bNqoXldo8wuSOMG5
; /kCrLNjrb6r9xK6+IDGQpzUG6/1Mm4v/cmMgT2NcV+h33ji89bAq6QuSaj8RamOwvhwpZeZ4//Kn+4
; njzRQJ5mXBntSdm2d2X0ioj8jcLNiTupO7kFAfkZnoAUqdmVz8lzPw10dkTwbrUnein1hd/DfL75fr
; D+zKgj2pM3X+pR/XH/iEHqDUnVkW/+VGHxHXFaTWRD/x7RfSjfHvVxNf3OgjDpAeoNSdOhb/5UYfcU
; D0AKXu1Ln4LzcG8gOgByh1ZrKf2MUXNwbyS8h1Bak7N06n+5N/p7Crz+LvIy4Rg3WpM5OD9VJ+v+Jz
; feuJ7RkaPaMHKE0lfq9iFlpKI2JyIWF8tkR/6AHKUBL9xJ0G/vqIPaEHKENIzkJCfcSCGazLUFJd/L
; fXwN9AvkB6gDKELNJPdP2hAHqAMpRM9hPnaWpYENgh1xVkCInrCrmL/3JjIN+itv+OnEhXmWfxX24M
; 5FtgsC5DySKL/3Kjj9ggPUAZQuJUdepQujr+vW9j9GEgXyODdRlKmlj8lxsLAmtgsC5DSAzWrxxL18
; e/9102NSwInIMFezKUtLn4LzfxRqOPmMmCPRlSfvXtrYugJX2hVF1IyBQG6zLElDKj3WkhYczRXH+Y
; 4LqCSLeZtpBQH7HiuSfT6n+v9OuHK7IsiYH/xZXtgf+0L7ritGUgv+n80bT+jwvmViJtZnLxX87AXx
; 9x5IuPpiN/ecNroUgbqfYT5xnJ6COO/PJ4uv7vn5X5Qxbpe+rsJ+ojjhzen1b//hOviCJ1ZpbFf7nR
; Rxx5+pF05Der6bqBvMhiWWTxX270EUde+3q6bCAvMl/qWPyXG33EkfFA3mlLJC9NLP7LjT7iyJvPpX
; UDeZHpiVfA5w80s/gvNzEfc/0hbZ22/vZjr4giO6XaA+y6QWIgP/LwQ2nfr79jIC9SzU+/uT1YL+Uv
; ScVp78ufd/XhY8efTq+4/iCylThNxdC7lDL15MDfQD5tvSJuDvluOG2JlJFpCwn1EUdiIH/vUr9+sC
; LLlpyFhPqII/qIIt1l1oG/PuKIPqJIe9lp8V/uf6uPOLLypIG8SNP502vpzqL9RAsCR6KPuP6igbxI
; 3YnBevUaRR39RH3EEX1Ekfpy80xz/UQD+RF9RJHFM7n4r6l+oj7iiIG8yOypc/FfbgzkR/QRRfLTxO
; K/3Ogjjjz2cDpoQaDI7mlj8V9uDORHTj6T1lx/EHkwbS7+y02ctlaeMpD/+BVx89jr+oPIW1tXFsav
; YdUeYNefqTrwJ1kQKFJNKVsfdhr4R+3H9YekjyhSUqb1E+MVMWpArj+kresPXhFFukmcqk4dSlfH/x
; 6nDfxjIO/6Q9JHFOkikwP/eCDt9d/oI47oI4q0k2mL/3Lj+sPI+aNpXR9RpJl8cG7vxX+50UccMZAX
; qT9N/aUfCwJH9BFFFs8ii/9yo484cnh/WtVHFJkvbfYT9RFHYiCvjyiSn/uXu+snGsiPxIJA1x9Epq
; fJxX+5idOWv4+YLAgUmZZqD/D4gbTa1OK/3FgQOKKPKPJgfvSN7RvrbSz+y0kM/J99fPsaxaDFaev9
; Na+IIpFx56+u6wqLpjrwp0IfUaScTC4kZAf6iCLdp9pPZA/6iCLdJPqJ105Y/DeX6CPeu9SvH7hIX3
; P3woP9ROagjyjSfKr9RGqgjyhSfyYX/1EjA3mR+mKw3oIYyG8OBV1/EJkzMVi/uLK9+I8WRB/RgkCR
; 2XL7bNpwquqIPqJIfqKfaLBeAH1Ekd0zufiPAsRpy4JAkQejB1iwhx9K+ywIFNED7JXVg64/yHDjuk
; IPxSvi5nFYH1EGk7iuUF38Rw8ZyMsQEq+Am28Wa4n+00eUZU70AA3Wl5AFgbJM0QMcAH1EWYYYrA+I
; BYHS18Rg/coxPcBB0keUPsWCPfQRpRexYI8HWBAoJUYPkF0d3p9W9RGllLz7susK7CEG8vqI0mVisK
; 4HyExiIO/6g7Sdm2dcV2BOMZB/7/V0x2lL2ogeILXQR5QmowdI7eK09f6aV0SpNxbs0Sh9RKkjFuzR
; Gn1EWSR6gLROH1FmTVxXuHbCYJ0OnT+a1vURZa/oAVIMCwJlWvQAKZI+olSjB0jxoo9oIC8xWHddgV
; 6IgfzmcNX1hwEmBusXVyzYo4csCBxWbp9NG64r0GsWBA4jeoAsFX3E5YzBOksrTlsWBC5P9ABZeg8/
; lPZZENjv6AEyOKsH9RH7GD1ABiteEd85qY/Yh8R1BYN1SFsD+XuX+vUPeEixYA8m6COWGT1AmEIfsY
; zEqerUoXQ1AdNZENhtDNZhRhYEtp8YrF85pgcIc9NHbCcfnLNgD2qhj9hs4rqCwTrUzEC+3ugBQsP0
; EeuJHiC0JAby+ojz5f5lPUDoxMln0prrD/m5ecZ1BehUvCK+93q647Q1PXqAUBALAneOHiAUSh/xwU
; QP0GAdChfXH4b8imjBHvTMUPuIeoDQU0PqI0YP8O0X0o0E9Nv5o2l9mfuIdy/oAcJSWdaBvAV7sMSW
; pY+oBwgDcXh/Wu1zH/HG6XTfdQUYkD72EWOwfnHFgj0YrFgQ+OG58k9bt8+mDdcVgOIXBOoBAp9SWh
; 9RDxCYKk5b7691/4powR6Qras+oh4gMJfjT7fbR9QDBBYSr4hN9xHjusK1EwbrQE2ij3jvUv0PKz1A
; oBF19xH1AIHGLdpHjMH6qUPpagJow7wLAg3WgU5EH3FzWJ51/UEPEChC9BGnLQjUAwSKslsfMXqABu
; tAkcZ9RAv2gF6I05YeIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAABAs/4PNeHMXufLa3sAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 400x300 6032
; iVBORw0KGgoAAAANSUhEUgAAAZAAAAEsCAYAAADtt+XCAAARc0lEQVR4Ae3dz4te133H8bMxJaLFMg
; QV3EZIKRGIRtiKVVrhMUwlHEiH4MgYNYMb7MpurYq2sfrbq6FQbZyFoN1lYUG8MYiiamPalbKpFyVU
; ILpoaYsgkGyy8J8w8TfwWM+POzPPj3vuPefe1xvemASSaKKZuc+5n+/5fFMCAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAABAx3zjK+lbT/9SOp4AAFiGr55Izz94Mz382d+k/fhn/OsEAMBhvHMh
; vRsPjmn/77vp0/j3nUYAAAvEw+EHV9K9+YfHtP/y7fTgS0+nUwkAgODFL6XtOGUc9vCYPo18+6vpzQ
; QAGDf/cCndXubBMe8//V6645UWAIyQCMb/8530eJ2Hx8QI2GNSKwEAxkFTUL6uAnYAGAHxSz6C8LYe
; HgJ2ABgBEXzneHA0nUYSAGAYROCd++ExfxrxSgsAKqaNoHyT04iAHQAq5K9fTHt9PDjmjTFhpxEAqI
; DpHqtS1KcFAIXT5nhujldaAnYAKIxleqxK0bgvABTCKj1WJZ1GLn9ZwA4AvbFuj1Xf3r2aPv3yM2k7
; AQC6pcSgfBn/58/S/vUL6c701xIXHAXsANABJQflh/nDP0z786eOyQVHfVoAkJGcPVY5/clfpv297f
; TgmS88Cc4PuuAoYAeAlumixyqHn7yd9rdOzo7uHpXbWFgFAC3RdY9VW37v6+nBs7/yJNtYNbeJsWSv
; tABgDfrssdrECMp3z6Xb01/LurlNfP36tABgBUrpsVrV+7uz47ltXHCMV1rx/4fTCAAcQs3jue+9lB
; 5Mfy1tX3CMgN24LwA0UPN47gvPzobeuS446tMCgCni1UyNQXmM5zYF5V3kNsZ9AYyemoPyK2fT3vTX
; 0vUJysIqAKNlKD1WfV9wtLAKwGioOSi/eTHdm/5aSrngaGEVgMEzxB6rUtSnBWCQ1LTwadoIym9dXq
; 7HqhQF7AAGQ40Ln8JHN9L+pdOzI7O1XHDUpwWgemoNyr//zfRwkx6rUvy7rdlKFQAonlrHc8MIy6df
; AdWc2/zmCWO+ACqi1l+4004C6SHlNgJ2AMVS68KnIRm5zc6Z2QuO07mNgB1AcdS68GlIzl9wjAdFU2
; 6jTwtAMdS68GkoRmZz/UK6M/13sswDPU4jXmkB6IWag/KhuOkFR31aADqn1oVPQzGC8r3t9i446tMC
; kJ1a70MMyU/eTvtbJ2czjDbu2+jTApCNIYzn1m7T/pE2H+j6tAC0Sq09VkMygvLdc7O3ynM+0I37At
; iYWnushuT93cX9I1080PVpAVibWnushmKcOt57KT2Y/jvp44EeU11eaQFYCuO5/RvjuS88O/vpv88H
; euQsxn0BHIqgvF9jPLcpKC/hgS5gB9CIHqv+jVdWV87O9liV+EAXsAP4HD1W/TvfY1X6A12fFgA9Vj
; 0bp46bF9O96b+Tmh7o+rSAESIo799Ne6xKMU4jp467wQ6MAj1W/Rth+Z/81pO8o9YHetMFRwADRI9V
; ecaJo9YHetMFxxg11qcFDAzjuWzLpguOcUdkcsFRwA4MhPhUKChnW65ywdG4L1AxgnK2ZWQ2ty6vvn
; /EwiqgQvRYsS0f3Uj7O2dmLziumttYWAVUgKCcbTp/wTFeSa37/WVhFVAwgnK2ZQTl1y+kO9PfX21c
; cNSnBRSGhU9s0y4uOArYgQKw8IltGUH53vbqQfm6WlgF9IignG35ydtpf+vk7N2Nrr6/LKwCOsR4Lt
; u0af9I14MYFlYBHaDHim3Z1GPV5yCGgB3IxCbjk+S8TT1WpQxiCNiBFrHwiW3Z1GNV4iCGPi2gBfRY
; sS1X6bEqRQurgDUQlLMtYzy3KSiv5ftLnxawAsZz2ZbxyurK2dkeq1obC77z3OzXAWAKPVZs23/7Tn
; o4eQUU/4xXQjX9+cPJBccEoBk9VsxlvAKqdfw7Ljg25TbGfYGkx4o8yKMuOBr3xajRY0UuusoFR31a
; GCWCcnLRdS846tPCKDCeSy7adMExRndXOaHr08KgEZSTizZdcFz3Aq0+LQyOWscnyZzGeO6ty3n2jw
; jYMQj0WJGLPrqR9nfOzF4MbHvUWJ8WqkaPFbno3auzQXnupml9WqgKQTm5aATl1y+kO9M/K12d0PVp
; oQosfCIXjaB8+tQR9HFCj/F5pxEUhx4rctFJj1WOoHxd4+c0/gwJKAHjueSi0WO1dXI2xC7lAq2AHb
; 2jx4ps9qgeq1I07oteiB8IPVbkrKv0WJWigB2doseKXHTdHqtSFLAjK4JyctGmHqtam6Y/eMXiKmRA
; UE42G5NW06+Aaj2hf/hqejyd2wAbIygnlzPuddR4gTZOUNfOz15wjA+MAnZsRHyqqukHgeRqzl9wjA
; +M0xccLazCWuixIofr5ILj9M/8YRccLazCUuixIodtXHCc3z+yTG5jYRUORY8VOWw3veAYr7Ti94TT
; CD7HeC45bNu+4BgBuz4tGM8lB26uC476tEbM/LQFyWHZdMExMoy2Lzga9x0ZgnJy2MZ47jpB+brq0x
; oJeqzI4Rrjubcu97d/RJ/WQBGUk8P20Y20v3Mm7U3/3PcxWWlh1cAQlJPD9u7V2aA8Mok+PzBOAnan
; kYrRY0UO2wjKr1+Y7bGK6pFS/nwC9kqptU6a5HLO91gFJU5W6tOqDEE5OVwnPVZ9BeXrqk+rcIznks
; M2eqy2Ts5e3qvpA6M+rUIRlJPDdtMeq1L8jz9Kn546bkqrCOJIGEFVTd9AJFd3+hVQrR8Ym3Ib9ERJ
; 0xYk8xsnjho/MB50wTG+Hn1aPaDHimQNxgXHS6dnHxLzFxzjoShg7wBBOcla/PDV9HjZ3EafVmZ+45
; n0/P9/t55vHpLjNC44Xjs/e8Fx2dxGn1ZGfvvX0rd++KYLgiTLdD4oX2d1hD6tjJx8Oj3/ty+mOz++
; We43EclxObngOP27apNX7hZWZWbnK+ndmKku7RuJ5LiMC4659o/o08pInEb++ffT45/+Vf/fRCTHZx
; cXHPVpZeb6hXRbwE6yKyMo3z2Xbk//Hsp9wVGfVkZiSisCdqcRkjm9vzu7f6TL1RFxuom28YT2OfZU
; Oi5gJ5nDOHW899JsUB53N7peHWFhVWZi3Pff3xKwk2zHGM+dD8r7bsQQsGckAvb3X073vNIiua4H9V
; iV0ohh3DczEbD/143+/6JJ1mX0WO2cSXvTv0/me6xKUZ9WRiJg//h1474kl/Pu1dmgPF4Vlb5/RJ9W
; ZiJgN+5L8iAjKP/srcVMj1VNqyPiIaJPKyP6tEg2GTfK5xc+1bg6InKbP35h9o4KWiQC9r/fTveM+5
; KcOL2zvNbVEU0XHJGJN55Lt/VpkZwYr4C6uhTYtvO5zWTlt3HfjOjTIlmzTRcc53MbAXtm/uKigJ1k
; Xc7vHwkOy20E7Bk5dyJt69MiWbqbXHC0sCojFlaRLNm44Hjp9Ozt81UvOOrTykwsrNKnRbIkP3w1PW
; 5z/4iAPSNxGvnoNQE7yX6NoPza+dkLjm3tH7GwKjP6tEj25XxQHq+dclxwtLAqIxZWkezSCMr3tmfH
; c3NfcJy+TIkMCNhJ5jZqVeb3j8QIbhf/2wL2zOjTIpnL7309PWgzKF9XAXtGJn1aXmmRbMOmHqu2gv
; J1tbAqM/q0SG7q/d3FHquSOrksrMqIPi2S69jUYxUhdnzyL+3Pqk8rM/q0SC5rjOf2FZRvoj6tjEz6
; tEr/JiDZj5v0WJWiPq2M6NMi2WS8sto5k/amf1+s2mNVilGrkpAPfVok5528AooR2T7Gcze1KbdBJv
; RpkZy3xgdHeNAFR31amYk+rf/+07q+WUgyjNym6YLjfG6jTysj+rRI1uaqFxz1aWXk2FPpuICdZA3e
; vbp4wTEuFR71n9OnlRl9WiRLtSkoj4xj1f8efVoZiYD91mV9WiTLcX7/SLDJ/hF9Wpl562sWVpHs19
; wXHPVpZSQCdn1aJPvw0WcfYC+dnj0l5LjgqE8rMxGw69Mi2ZVxo7zr/SP6tDIiYCeZ2wjKr51Pd6Z/
; 93S5f0SfVkYmC6uM+5Js2/mgPE4DmwTl6ypgz0z0aVlYRbINIyjf254dzy2hCdi4b0YsrCK5qQf1WJ
; Xy5xOwZ8bCKpLr2NRjVWqho4A9I5OFVU4jJI9y1R6rUhSwZ8TCKpJHeX93scfqB1fSvVr+/Pq0MmNh
; Fcl5m4LyyBbiF3JNX0f4o3fS/q/+snA9G3Ea+eCV9NArLZITp18BlRSUr+J8boOMxMIqfVokJ8aJo+
; /x3HVsym3QAdGn9fHrxn1J1ul8boMeELCTrMmm/SPoEX1aJGuw6YIjCmDSp+WVFsnSjGkxQXkFvPFc
; uq1Pi2QpCsorQ58WyRK8e1VQXi36tEj2oaB8IOjTItml8/tHUDn6tEjmNoLyW5fTg2e+oI5kkOjTIp
; nDRzfS/qXTtg0OnjiNfPSagJ1kO0ZQbjx3ZOjTIrmJEZRfO5/uJIyT6NMSsJNcVUE5PkfATnIZm/aP
; APq0SB6qHiscij4tkk3qscLSRJ+WgJ2kHiushT4tctxa+ISN0adFjks9VmgVATs5DmM8V1CO1tGnRQ
; 5XPVbohOjTsrCKHI7RY7VzJu0loAsE7OQwtPAJvRF9WgJ2sj4jKP/s51ePFfpFnxZZl3qsUBRfPJZO
; CdjJsp30WAnKUSQx7mthFVme0WO1ddLCJxROBOzvv6xPiyxFPVaoDguryH7VY4WqiYD949eN+5Jdq8
; cKgyECduO+ZH71WGGQ6NMi86rHCoPGwiqyfWM8V1CO0RALq/RpkZsbr6yunNVjhZGhT4vcTD1WGD0W
; VpGrGaeOmxfTvQQgpXMn0rY+LfJo9VgBDVhYRR6shU/AEsTCKn1a5BNj4dOl03qsgKWI08hHrwnYye
; 9/Mz00ngusgT4tjtUIyq+dt/AJ2AgLqzg2//UPjOcCrSJg59CNoFyPFZAJfVocqrHwSY8VkBl9Whya
; eqyAjtGnxdq18AnoEX1arFULn4BC0KfFWrTwCSiQSZ9WTb9MOC71WAEFo0+LJarHCqiI6NMSsLMEo8
; dq54yFT0BV6NNi31r4BFRO9GkJ2NmleqyAAaFPi10pKAcGyLGn0nEBO3MZQfnetqAcGDTRp2VhFds0
; eqy2Tlr4BIyCCNhvXdanxc3VYwWMlLe+ZmEV11OPFYBfBOz3d437cnn1WAGYIQJ24748TD1WAA7Ewi
; oeZIznWvgE4FAmC6uM+zKM8VxBOYCV0KfFeGV15aweKwBrYGHVeNVjBaAVLKwaj3HquH5BjxWAFpks
; rHIaGa56rABkw8KqYWrhE4DOiIBdn9Yw/NE7af/SaT1WADokTiMfvJIeeqWVqvUfv2E8F0CPxMIqfV
; p1qccKQDFYWFWPeqwAFImAvVwfv6vHCkDh6NMqz1j4pMcKQBVM+rS80upfPVYAquSN59JtfVr9KCgH
; UD36tLpXjxWAQaFPK78WPgEYLJM+rZp+KdeiHisAg0efVrvqsQIwOvRpbe6jG2l/54yFTwBGSJxGPn
; pNwL6OEZQbzwUwevRpLW8E5dfOW/gEAJ+jT+toBeUAcADHnkrHBeyLRlC+t208FwCORJ/WE6PHauuk
; hU8AsDT6tPRYAcBGRJ/W2AJ2PVYA0BJj6tOy8AkAMjDkPi09VgCQmSEG7DGea+ETAHTAUPq09FgBQE
; 9En1atC6vilZUeKwDokRoDdgufAKAgagjY49Rx/YIeKwAojpL7tPRYAUDhfPFYOlVSwD7psRKUA0Al
; /O6p9GbfC6v0WAFApUTA/v7L/fRp6bECgAHQ5cIqPVYAMDAiYP/49bzjvnqsAGDA5AjY9VgBwEhos0
; 9LjxUAjIxNF1bFeK6gHABGTCysWrVPS1AOAPgFq/Rp6bECACxwWJ9WnDpuXkz3EgAATZw7kbbn+7T0
; WAEAlmKysOp//9zCJwDAGvzOrxvPBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6J6fA4
; PTKOvoVPDWAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 32x32 584
; iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABfUlEQVR4Ae1WPUsDQRSczkaINgpCQB
; S7FCkUhICKIEGrWChBENJILAIR/GgE09iqhT8gYCmCgpXV1TaelVgEUiVNivsJCUNYsiSXzX28Owjc
; wIM9uLsZ5s3uPiBBgmlDMYPSRxFWOoVlxI3nA9Q7N+iyKCKXxg7iQGYB2Z8ymorcKsFWz/e7eEKUuM
; 6hpoiHq3XZd4KCKBKS4A/543Hkygl9zXykZjCHsCiv48JEPFx0QbWEawQF1etB81u/53Bej2A1qnDo
; hh/ukaAFKf37zxPYdNJTS5jkMMRuLdGzYdyuVEgB7Ss5ATr51ylstmSiG1T5X4EjKYDEuivMl/EEDR
; tCkxNq/VfxEFC+oKuXKoZUiaEjxpZwV7wdD8IkXXfbHo5wFVBJN3hWbCz5vMQY0LBnBOshjzqCgm48
; 5oMFlJfW/hoKkMDeCgp+WsLQLc4KDy+r88i+HOJ9Enl1EzVEidst94BGMh+MA4m+zwYBjXxCcgMDys
; lJLGgJEsSJHlWB8GOqYq+hAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.42mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=FirstLayerCalibration-FirstLayer.stl_id_0_copy_0 CENTER=175,175 POLYGON=[[145,131.8],[205,131.8],[205,218.2],[145,218.2],[145,131.8]]
M73 P0 R2
;TYPE:Custom
M104 S0
M140 S0
START_PRINT EXTRUDER_TEMP=235 BED_TEMP=55 MATERIAL=PLA
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
M106 S0
;LAYER_CHANGE
;Z:0.25
;HEIGHT:0.25
G92 E0
G1 E-.5 F1800
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=3000 ACCEL_TO_DECEL=1500
G1 Z.65 F36000
G1 X144.777 Y137.59
G1 Z.65
G1 Z.25
G1 E.5 F1800
;TYPE:Skirt
;WIDTH:0.5
G1 F3000
G1 X144.777 Y131.8 E.26324
G1 X145 Y131.577 E.01435
G1 X205 Y131.577 E2.72789
G1 X205.223 Y131.8 E.01435
M73 P1 R2
G1 X205.223 Y218.2 E3.92816
G1 X205 Y218.423 E.01435
M73 P2 R2
G1 X145 Y218.423 E2.72789
G1 X144.777 Y218.2 E.01435
M73 P3 R2
G1 X144.777 Y137.63 E3.6631
; printing object FirstLayerCalibration-FirstLayer.stl id:0 copy 0
;WIPE_START
G1 X144.777 Y135.63 E-.5
M73 P4 R2
;WIPE_END
EXCLUDE_OBJECT_START NAME=FirstLayerCalibration-FirstLayer.stl_id_0_copy_0
G1 Z.65 F36000
G1 X194.65 Y151.55 Z.65
G1 Z.25
G1 E.5 F1800
;TYPE:Outer wall
G1 X204.65 Y151.55 E.45465
G1 X204.65 Y159.65 E.36826
G1 X194.65 Y159.65 E.45465
G1 X194.65 Y161.25 E.07274
G1 X204.65 Y161.25 E.45465
M73 P5 R2
G1 X204.65 Y169.35 E.36826
G1 X194.65 Y169.35 E.45465
G1 X194.65 Y170.95 E.07274
G1 X204.65 Y170.95 E.45465
G1 X204.65 Y179.05 E.36826
G1 X194.65 Y179.05 E.45465
M73 P6 R2
G1 X194.65 Y180.65 E.07274
G1 X204.65 Y180.65 E.45465
G1 X204.65 Y188.75 E.36826
G1 X194.65 Y188.75 E.45465
G1 X194.65 Y190.35 E.07274
G1 X204.65 Y190.35 E.45465
G1 X204.65 Y198.45 E.36826
M73 P7 R2
G1 X194.65 Y198.45 E.45465
G1 X194.65 Y200.05 E.07274
G1 X204.65 Y200.05 E.45465
G1 X204.65 Y208.15 E.36826
G1 X194.65 Y208.15 E.45465
G1 X194.65 Y209.75 E.07274
M73 P8 R2
G1 X204.65 Y209.75 E.45465
G1 X204.65 Y217.85 E.36826
G1 X145.35 Y217.85 E2.69606
G1 X145.35 Y132.15 E3.89633
M73 P9 R2
G1 X204.65 Y132.15 E2.69606
M73 P11 R2
G1 X204.65 Y140.25 E.36826
M73 P12 R2
G1 X194.65 Y140.25 E.45465
G1 X194.65 Y141.85 E.07274
M73 P13 R2
G1 X204.65 Y141.85 E.45465
G1 X204.65 Y149.95 E.36826
G1 X194.65 Y149.95 E.45465
G1 X194.65 Y151.53 E.07183
G1 X194.204 Y151.996 F36000
;TYPE:Inner wall
G1 F1800
G1 X204.204 Y151.996 E.45465
G1 X204.204 Y159.204 E.32768
M73 P14 R2
G1 X194.204 Y159.204 E.45465
G1 X194.204 Y161.696 E.11333
G1 X204.204 Y161.696 E.45465
G1 X204.204 Y168.904 E.32768
G1 X194.204 Y168.904 E.45465
G1 X194.204 Y171.396 E.11333
M73 P15 R2
G1 X204.204 Y171.396 E.45465
G1 X204.204 Y178.604 E.32768
G1 X194.204 Y178.604 E.45465
G1 X194.204 Y181.096 E.11333
G1 X204.204 Y181.096 E.45465
G1 X204.204 Y188.304 E.32768
G1 X194.204 Y188.304 E.45465
M73 P16 R2
G1 X194.204 Y190.796 E.11333
G1 X204.204 Y190.796 E.45465
G1 X204.204 Y198.004 E.32768
G1 X194.204 Y198.004 E.45465
G1 X194.204 Y200.496 E.11333
G1 X204.204 Y200.496 E.45465
G1 X204.204 Y207.704 E.32768
M73 P17 R2
G1 X194.204 Y207.704 E.45465
G1 X194.204 Y210.196 E.11333
G1 X204.204 Y210.196 E.45465
G1 X204.204 Y217.404 E.32768
G1 X145.796 Y217.404 E2.65548
G1 X145.796 Y132.596 E3.85575
M73 P19 R2
G1 X204.204 Y132.596 E2.65548
M73 P20 R2
G1 X204.204 Y139.804 E.32768
M73 P22 R2
G1 X194.204 Y139.804 E.45465
G1 X194.204 Y142.296 E.11333
G1 X204.204 Y142.296 E.45465
G1 X204.204 Y149.504 E.32768
G1 X194.204 Y149.504 E.45465
G1 X194.204 Y151.976 E.11242
M73 P23 R2
;WIPE_START
G1 X196.204 Y151.98 E-.5
;WIPE_END
G1 Z.65 F36000
G1 X145.93 Y132.932 Z.65
G1 Z.25
G1 E.5 F1800
;TYPE:Bottom surface
;WIDTH:0.501185
G1 F5400
G1 X203.869 Y132.932 E2.64116
G1 X203.869 Y133.379 E.0204
G1 X146.131 Y133.379 E2.63201
G1 X146.131 Y133.827 E.0204
M73 P24 R2
G1 X203.869 Y133.827 E2.63201
G1 X203.869 Y134.274 E.0204
G1 X146.131 Y134.274 E2.63201
G1 X146.131 Y134.722 E.0204
M73 P25 R1
G1 X203.869 Y134.722 E2.63201
G1 X203.869 Y135.169 E.0204
G1 X146.131 Y135.169 E2.63201
G1 X146.131 Y135.617 E.0204
G1 X203.869 Y135.617 E2.63201
M73 P26 R1
G1 X203.869 Y136.065 E.0204
G1 X146.131 Y136.065 E2.63201
G1 X146.131 Y136.512 E.0204
G1 X203.869 Y136.512 E2.63201
G1 X203.869 Y136.96 E.0204
M73 P27 R1
G1 X146.131 Y136.96 E2.63201
G1 X146.131 Y137.407 E.0204
G1 X203.869 Y137.407 E2.63201
G1 X203.869 Y137.855 E.0204
M73 P28 R1
G1 X146.131 Y137.855 E2.63201
G1 X146.131 Y138.302 E.0204
G1 X203.869 Y138.302 E2.63201
G1 X203.869 Y138.75 E.0204
G1 X146.131 Y138.75 E2.63201
G1 X146.131 Y139.197 E.0204
M73 P29 R1
G1 X203.869 Y139.197 E2.63201
G1 X203.869 Y139.469 E.01238
G1 X193.869 Y139.469 E.45586
G1 X193.869 Y139.645 E.00802
G1 X146.131 Y139.645 E2.17615
G1 X146.131 Y140.092 E.0204
M73 P30 R1
G1 X193.869 Y140.092 E2.17615
G1 X193.869 Y140.54 E.0204
G1 X146.131 Y140.54 E2.17615
G1 X146.131 Y140.987 E.0204
G1 X193.869 Y140.987 E2.17615
G1 X193.869 Y141.435 E.0204
M73 P31 R1
G1 X146.131 Y141.435 E2.17615
G1 X146.131 Y141.882 E.0204
G1 X193.869 Y141.882 E2.17615
G1 X193.869 Y142.33 E.0204
M73 P32 R1
G1 X146.131 Y142.33 E2.17615
G1 X146.131 Y142.778 E.0204
G1 X203.869 Y142.778 E2.63201
G1 X203.869 Y143.225 E.0204
G1 X146.131 Y143.225 E2.63201
G1 X146.131 Y143.673 E.0204
M73 P33 R1
G1 X203.869 Y143.673 E2.63201
G1 X203.869 Y144.12 E.0204
G1 X146.131 Y144.12 E2.63201
G1 X146.131 Y144.568 E.0204
M73 P34 R1
G1 X203.869 Y144.568 E2.63201
G1 X203.869 Y145.015 E.0204
G1 X146.131 Y145.015 E2.63201
G1 X146.131 Y145.463 E.0204
G1 X203.869 Y145.463 E2.63201
G1 X203.869 Y145.91 E.0204
M73 P35 R1
G1 X146.131 Y145.91 E2.63201
G1 X146.131 Y146.358 E.0204
G1 X203.869 Y146.358 E2.63201
G1 X203.869 Y146.805 E.0204
M73 P36 R1
G1 X146.131 Y146.805 E2.63201
G1 X146.131 Y147.253 E.0204
G1 X203.869 Y147.253 E2.63201
G1 X203.869 Y147.7 E.0204
M73 P37 R1
G1 X146.131 Y147.7 E2.63201
G1 X146.131 Y148.148 E.0204
G1 X203.869 Y148.148 E2.63201
G1 X203.869 Y148.595 E.0204
G1 X146.131 Y148.595 E2.63201
G1 X146.131 Y149.043 E.0204
M73 P38 R1
G1 X203.869 Y149.043 E2.63201
G1 X203.869 Y149.169 E.00574
G1 X193.869 Y149.169 E.45586
G1 X193.869 Y149.491 E.01466
G1 X146.131 Y149.491 E2.17615
G1 X146.131 Y149.938 E.0204
M73 P39 R1
G1 X193.869 Y149.938 E2.17615
G1 X193.869 Y150.386 E.0204
G1 X146.131 Y150.386 E2.17615
G1 X146.131 Y150.833 E.0204
G1 X193.869 Y150.833 E2.17615
G1 X193.869 Y151.281 E.0204
M73 P40 R1
G1 X146.131 Y151.281 E2.17615
G1 X146.131 Y151.728 E.0204
G1 X193.869 Y151.728 E2.17615
G1 X193.869 Y152.176 E.0204
G1 X146.131 Y152.176 E2.17615
G1 X146.131 Y152.623 E.0204
M73 P41 R1
G1 X203.869 Y152.623 E2.63201
G1 X203.869 Y153.071 E.0204
G1 X146.131 Y153.071 E2.63201
G1 X146.131 Y153.518 E.0204
M73 P42 R1
G1 X203.869 Y153.518 E2.63201
G1 X203.869 Y153.966 E.0204
G1 X146.131 Y153.966 E2.63201
G1 X146.131 Y154.413 E.0204
G1 X203.869 Y154.413 E2.63201
G1 X203.869 Y154.861 E.0204
M73 P43 R1
G1 X146.131 Y154.861 E2.63201
G1 X146.131 Y155.309 E.0204
G1 X203.869 Y155.309 E2.63201
G1 X203.869 Y155.756 E.0204
M73 P44 R1
G1 X146.131 Y155.756 E2.63201
G1 X146.131 Y156.204 E.0204
G1 X203.869 Y156.204 E2.63201
G1 X203.869 Y156.651 E.0204
M73 P45 R1
G1 X146.131 Y156.651 E2.63201
G1 X146.131 Y157.099 E.0204
G1 X203.869 Y157.099 E2.63201
G1 X203.869 Y157.546 E.0204
G1 X146.131 Y157.546 E2.63201
G1 X146.131 Y157.994 E.0204
M73 P46 R1
G1 X203.869 Y157.994 E2.63201
G1 X203.869 Y158.441 E.0204
G1 X146.131 Y158.441 E2.63201
G1 X146.131 Y158.889 E.0204
M73 P47 R1
G1 X193.869 Y158.889 E2.17615
G1 X193.869 Y159.336 E.0204
G1 X146.131 Y159.336 E2.17615
G1 X146.131 Y159.784 E.0204
G1 X193.869 Y159.784 E2.17615
G1 X193.869 Y160.231 E.0204
M73 P48 R1
G1 X146.131 Y160.231 E2.17615
G1 X146.131 Y160.679 E.0204
G1 X193.869 Y160.679 E2.17615
G1 X193.869 Y161.126 E.0204
G1 X146.131 Y161.126 E2.17615
G1 X146.131 Y161.574 E.0204
M73 P49 R1
G1 X193.869 Y161.574 E2.17615
G1 X193.869 Y162.022 E.0204
G1 X146.131 Y162.022 E2.17615
G1 X146.131 Y162.469 E.0204
G1 X203.869 Y162.469 E2.63201
M73 P50 R1
G1 X203.869 Y162.917 E.0204
G1 X146.131 Y162.917 E2.63201
G1 X146.131 Y163.364 E.0204
G1 X203.869 Y163.364 E2.63201
G1 X203.869 Y163.812 E.0204
M73 P51 R1
G1 X146.131 Y163.812 E2.63201
G1 X146.131 Y164.259 E.0204
G1 X203.869 Y164.259 E2.63201
G1 X203.869 Y164.707 E.0204
M73 P52 R1
G1 X146.131 Y164.707 E2.63201
G1 X146.131 Y165.154 E.0204
G1 X203.869 Y165.154 E2.63201
G1 X203.869 Y165.602 E.0204
G1 X146.131 Y165.602 E2.63201
G1 X146.131 Y166.049 E.0204
M73 P53 R1
G1 X203.869 Y166.049 E2.63201
G1 X203.869 Y166.497 E.0204
G1 X146.131 Y166.497 E2.63201
G1 X146.131 Y166.944 E.0204
M73 P54 R1
G1 X203.869 Y166.944 E2.63201
G1 X203.869 Y167.392 E.0204
G1 X146.131 Y167.392 E2.63201
G1 X146.131 Y167.839 E.0204
M73 P55 R1
G1 X203.869 Y167.839 E2.63201
G1 X203.869 Y168.287 E.0204
G1 X146.131 Y168.287 E2.63201
G1 X146.131 Y168.735 E.0204
G1 X193.869 Y168.735 E2.17615
G1 X193.869 Y169.182 E.0204
M73 P56 R1
G1 X146.131 Y169.182 E2.17615
G1 X146.131 Y169.63 E.0204
G1 X193.869 Y169.63 E2.17615
G1 X193.869 Y170.077 E.0204
G1 X146.131 Y170.077 E2.17615
G1 X146.131 Y170.525 E.0204
M73 P57 R1
G1 X193.869 Y170.525 E2.17615
G1 X193.869 Y170.972 E.0204
G1 X146.131 Y170.972 E2.17615
G1 X146.131 Y171.42 E.0204
M73 P58 R1
G1 X193.869 Y171.42 E2.17615
G1 X193.869 Y171.731 E.01419
G1 X203.869 Y171.731 E.45586
G1 X203.869 Y171.867 E.00621
G1 X146.131 Y171.867 E2.63201
G1 X146.131 Y172.315 E.0204
G1 X203.869 Y172.315 E2.63201
G1 X203.869 Y172.762 E.0204
M73 P59 R1
G1 X146.131 Y172.762 E2.63201
G1 X146.131 Y173.21 E.0204
G1 X203.869 Y173.21 E2.63201
G1 X203.869 Y173.657 E.0204
M73 P60 R1
G1 X146.131 Y173.657 E2.63201
G1 X146.131 Y174.105 E.0204
G1 X203.869 Y174.105 E2.63201
G1 X203.869 Y174.553 E.0204
M73 P61 R1
G1 X146.131 Y174.553 E2.63201
G1 X146.131 Y175 E.0204
G1 X203.869 Y175 E2.63201
G1 X203.869 Y175.448 E.0204
G1 X146.131 Y175.448 E2.63201
G1 X146.131 Y175.895 E.0204
M73 P62 R1
G1 X203.869 Y175.895 E2.63201
G1 X203.869 Y176.343 E.0204
M73 P62 R0
G1 X146.131 Y176.343 E2.63201
G1 X146.131 Y176.79 E.0204
M73 P63 R0
G1 X203.869 Y176.79 E2.63201
G1 X203.869 Y177.238 E.0204
G1 X146.131 Y177.238 E2.63201
G1 X146.131 Y177.685 E.0204
G1 X203.869 Y177.685 E2.63201
G1 X203.869 Y178.133 E.0204
M73 P64 R0
G1 X146.131 Y178.133 E2.63201
G1 X146.131 Y178.58 E.0204
G1 X193.869 Y178.58 E2.17615
G1 X193.869 Y179.028 E.0204
M73 P65 R0
G1 X146.131 Y179.028 E2.17615
G1 X146.131 Y179.475 E.0204
G1 X193.869 Y179.475 E2.17615
G1 X193.869 Y179.923 E.0204
G1 X146.131 Y179.923 E2.17615
G1 X146.131 Y180.37 E.0204
M73 P66 R0
G1 X193.869 Y180.37 E2.17615
G1 X193.869 Y180.818 E.0204
G1 X146.131 Y180.818 E2.17615
G1 X146.131 Y181.266 E.0204
G1 X193.869 Y181.266 E2.17615
G1 X193.869 Y181.431 E.00755
M73 P67 R0
G1 X203.869 Y181.431 E.45586
G1 X203.869 Y181.713 E.01285
G1 X146.131 Y181.713 E2.63201
G1 X146.131 Y182.161 E.0204
G1 X203.869 Y182.161 E2.63201
G1 X203.869 Y182.608 E.0204
M73 P68 R0
G1 X146.131 Y182.608 E2.63201
G1 X146.131 Y183.056 E.0204
G1 X203.869 Y183.056 E2.63201
G1 X203.869 Y183.503 E.0204
M73 P69 R0
G1 X146.131 Y183.503 E2.63201
G1 X146.131 Y183.951 E.0204
G1 X203.869 Y183.951 E2.63201
G1 X203.869 Y184.398 E.0204
G1 X146.131 Y184.398 E2.63201
G1 X146.131 Y184.846 E.0204
M73 P70 R0
G1 X203.869 Y184.846 E2.63201
G1 X203.869 Y185.293 E.0204
G1 X146.131 Y185.293 E2.63201
G1 X146.131 Y185.741 E.0204
M73 P71 R0
G1 X203.869 Y185.741 E2.63201
G1 X203.869 Y186.188 E.0204
G1 X146.131 Y186.188 E2.63201
G1 X146.131 Y186.636 E.0204
M73 P72 R0
G1 X203.869 Y186.636 E2.63201
G1 X203.869 Y187.084 E.0204
G1 X146.131 Y187.083 E2.63201
G1 X146.131 Y187.531 E.0204
G1 X203.869 Y187.531 E2.63201
G1 X203.869 Y187.969 E.01996
M73 P73 R0
G1 X146.131 Y187.979 E2.63201
G1 X146.131 Y188.426 E.0204
G1 X193.869 Y188.426 E2.17615
G1 X193.869 Y188.874 E.0204
M73 P74 R0
G1 X146.131 Y188.874 E2.17615
G1 X146.131 Y189.321 E.0204
G1 X193.869 Y189.321 E2.17615
G1 X193.869 Y189.769 E.0204
G1 X146.131 Y189.769 E2.17615
G1 X146.131 Y190.216 E.0204
M73 P75 R0
G1 X193.869 Y190.216 E2.17615
G1 X193.869 Y190.664 E.0204
G1 X146.131 Y190.664 E2.17615
G1 X146.131 Y191.111 E.0204
G1 X193.869 Y191.111 E2.17615
G1 X193.869 Y191.131 E.0009
M73 P76 R0
G1 X203.869 Y191.131 E.45586
G1 X203.869 Y191.559 E.0195
G1 X146.131 Y191.559 E2.63201
G1 X146.131 Y192.006 E.0204
G1 X203.869 Y192.006 E2.63201
G1 X203.869 Y192.454 E.0204
M73 P77 R0
G1 X146.131 Y192.454 E2.63201
G1 X146.131 Y192.901 E.0204
G1 X203.869 Y192.901 E2.63201
G1 X203.869 Y193.349 E.0204
G1 X146.131 Y193.349 E2.63201
G1 X146.131 Y193.797 E.0204
M73 P78 R0
G1 X203.869 Y193.797 E2.63201
G1 X203.869 Y194.244 E.0204
G1 X146.131 Y194.244 E2.63201
G1 X146.131 Y194.692 E.0204
M73 P79 R0
G1 X203.869 Y194.692 E2.63201
G1 X203.869 Y195.139 E.0204
G1 X146.131 Y195.139 E2.63201
G1 X146.131 Y195.587 E.0204
M73 P80 R0
G1 X203.869 Y195.587 E2.63201
G1 X203.869 Y196.034 E.0204
G1 X146.131 Y196.034 E2.63201
G1 X146.131 Y196.482 E.0204
G1 X203.869 Y196.482 E2.63201
G1 X203.869 Y196.929 E.0204
M73 P81 R0
G1 X146.131 Y196.929 E2.63201
G1 X146.131 Y197.377 E.0204
G1 X203.869 Y197.377 E2.63201
G1 X203.869 Y197.669 E.01331
M73 P82 R0
G1 X193.869 Y197.669 E.45586
G1 X193.869 Y197.824 E.00709
G1 X146.131 Y197.824 E2.17615
G1 X146.131 Y198.272 E.0204
G1 X193.869 Y198.272 E2.17615
G1 X193.869 Y198.719 E.0204
G1 X146.131 Y198.719 E2.17615
G1 X146.131 Y199.167 E.0204
M73 P83 R0
G1 X193.869 Y199.167 E2.17615
G1 X193.869 Y199.614 E.0204
G1 X146.131 Y199.614 E2.17615
G1 X146.131 Y200.062 E.0204
M73 P84 R0
G1 X193.869 Y200.062 E2.17615
G1 X193.869 Y200.51 E.0204
G1 X146.131 Y200.51 E2.17615
G1 X146.131 Y200.957 E.0204
G1 X203.869 Y200.957 E2.63201
G1 X203.869 Y201.405 E.0204
M73 P85 R0
G1 X146.131 Y201.405 E2.63201
G1 X146.131 Y201.852 E.0204
G1 X203.869 Y201.852 E2.63201
G1 X203.869 Y202.3 E.0204
G1 X146.131 Y202.3 E2.63201
M73 P86 R0
G1 X146.131 Y202.747 E.0204
G1 X203.869 Y202.747 E2.63201
G1 X203.869 Y203.195 E.0204
G1 X146.131 Y203.195 E2.63201
G1 X146.131 Y203.642 E.0204
M73 P87 R0
G1 X203.869 Y203.642 E2.63201
G1 X203.869 Y204.09 E.0204
G1 X146.131 Y204.09 E2.63201
G1 X146.131 Y204.537 E.0204
M73 P88 R0
G1 X203.869 Y204.537 E2.63201
G1 X203.869 Y204.985 E.0204
G1 X146.131 Y204.985 E2.63201
G1 X146.131 Y205.432 E.0204
G1 X203.869 Y205.432 E2.63201
G1 X203.869 Y205.88 E.0204
M73 P89 R0
G1 X146.131 Y205.88 E2.63201
G1 X146.131 Y206.328 E.0204
G1 X203.869 Y206.328 E2.63201
G1 X203.869 Y206.775 E.0204
M73 P90 R0
G1 X146.131 Y206.775 E2.63201
G1 X146.131 Y207.223 E.0204
G1 X203.869 Y207.223 E2.63201
G1 X203.869 Y207.369 E.00667
M73 P91 R0
G1 X193.869 Y207.369 E.45586
G1 X193.869 Y207.67 E.01373
G1 X146.131 Y207.67 E2.17615
G1 X146.131 Y208.118 E.0204
G1 X193.869 Y208.118 E2.17615
G1 X193.869 Y208.565 E.0204
G1 X146.131 Y208.565 E2.17615
G1 X146.131 Y209.013 E.0204
M73 P92 R0
G1 X193.869 Y209.013 E2.17615
G1 X193.869 Y209.46 E.0204
G1 X146.131 Y209.46 E2.17615
G1 X146.131 Y209.908 E.0204
G1 X193.869 Y209.908 E2.17615
G1 X193.869 Y210.355 E.0204
M73 P93 R0
G1 X146.131 Y210.355 E2.17615
G1 X146.131 Y210.803 E.0204
G1 X203.869 Y210.803 E2.63201
G1 X203.869 Y211.25 E.0204
M73 P94 R0
G1 X146.131 Y211.25 E2.63201
G1 X146.131 Y211.698 E.0204
G1 X203.869 Y211.698 E2.63201
G1 X203.869 Y212.145 E.0204
G1 X146.131 Y212.145 E2.63201
G1 X146.131 Y212.593 E.0204
M73 P95 R0
G1 X203.869 Y212.593 E2.63201
G1 X203.869 Y213.041 E.0204
G1 X146.131 Y213.041 E2.63201
G1 X146.131 Y213.488 E.0204
M73 P96 R0
G1 X203.869 Y213.488 E2.63201
G1 X203.869 Y213.936 E.0204
G1 X146.131 Y213.936 E2.63201
G1 X146.131 Y214.383 E.0204
M73 P97 R0
G1 X203.869 Y214.383 E2.63201
G1 X203.869 Y214.831 E.0204
G1 X146.131 Y214.831 E2.63201
G1 X146.131 Y215.278 E.0204
G1 X203.869 Y215.278 E2.63201
G1 X203.869 Y215.726 E.0204
M73 P98 R0
G1 X146.131 Y215.726 E2.63201
G1 X146.131 Y216.173 E.0204
G1 X203.869 Y216.173 E2.63201
G1 X203.869 Y216.621 E.0204
M73 P99 R0
G1 X146.131 Y216.621 E2.63201
G1 X146.131 Y217.068 E.0204
G1 X204.07 Y217.068 E2.64116
; stop printing object FirstLayerCalibration-FirstLayer.stl id:0 copy 0
;WIPE_START
G1 F5400
G1 X202.07 Y217.068 E-.5
;WIPE_END
EXCLUDE_OBJECT_END NAME=FirstLayerCalibration-FirstLayer.stl_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode
END_PRINT
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 532.63
; filament used [cm3] = 1.28
; filament used [g] = 1.59
; filament cost = 0.03
; total filament used [g] = 1.59
; total filament cost = 0.03
; total layers count = 1
; estimated printing time (normal mode) = 2m 39s
; estimated first layer printing time (normal mode) = 0.667414s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 70
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = G92 E0
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 100%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0
; brim_type = auto_brim
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = Textured PEI Plate
; default_acceleration = 20000
; default_bed_type = 
; default_filament_colour = ""
; default_filament_profile = "Sovol SV08 PLA"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @Sovol SV08
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 1
; different_settings_to_system = brim_type;infill_direction;solid_infill_direction;sparse_infill_density;;before_layer_change_gcode;machine_start_gcode;print_host;support_multi_bed_types
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0.1
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #FF8000
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 50
; fan_kickstart = 0
; fan_max_speed = 70
; fan_min_speed = 50
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode\n"
; filament_flow_ratio = 0.98
; filament_ids = GFL99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 21
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Sovol SV08 PLA"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; Filament gcode\n"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{layer_height}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 3
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = nowhere
; gap_infill_speed = 200
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 65
; hot_plate_temp_initial_layer = 65
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 0
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 30%
; inherits_group = ;;"Sovol SV08 0.4 nozzle"
; initial_layer_acceleration = 3000
; initial_layer_infill_speed = 90
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.25
; initial_layer_speed = 30
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 12000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.42
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 1
; internal_bridge_speed = 50
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.45
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 200
; ironing_angle = -1
; ironing_fan_speed = -1
; ironing_flow = 15%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.25
; ironing_speed = 15
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.4
; long_retractions_when_cut = 0
; machine_end_gcode = END_PRINT\n
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 5000
; machine_max_acceleration_travel = 40000
; machine_max_acceleration_x = 40000
; machine_max_acceleration_y = 40000
; machine_max_acceleration_z = 500
; machine_max_jerk_e = 5
; machine_max_jerk_x = 20
; machine_max_jerk_y = 20
; machine_max_jerk_z = 0.5
; machine_max_junction_deviation = 0,0
; machine_max_speed_e = 50
; machine_max_speed_x = 700
; machine_max_speed_y = 700
; machine_max_speed_z = 20
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = PAUSE
; machine_start_gcode = M104 S0\nM140 S0\nSTART_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single] MATERIAL=[filament_type]
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 235
; nozzle_temperature_range_high = 250
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 8000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.4
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "Sovol SV08 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Sovol SV08 0.4 nozzle
; printable_area = 0x0,350x0,350x350,0x350
; printable_height = 345
; printer_model = Sovol SV08
; printer_notes = 
; printer_settings_id = SV08 - 0.4mm
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 0%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 343
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.5
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 5%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 0
; skirt_height = 1
; skirt_loops = 1
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 5
; slow_down_layers = 3
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 0
; solid_infill_filament = 1
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 100%
; sparse_infill_density = 0%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = crosshatch
; sparse_infill_rotate_template = 
; sparse_infill_speed = 300
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 45
; supertack_plate_temp_initial_layer = 45
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = -1
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 0.45
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 1
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 80
; support_style = snug
; support_threshold_angle = 20
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 55
; textured_plate_temp_initial_layer = 55
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 300x300/PNG, 400x300/PNG, 32x32/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 4
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 12000
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 20000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 600
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 40
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 2
; wall_sequence = outer wall/inner wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 2
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 55
; bed_shape = 0x0,350x0,350x350,0x350
; first_layer_temperature = 235
; first_layer_height = 0.250
; CONFIG_BLOCK_END


